# Generated by Django 4.2.6 on 2023-10-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cred_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'login_cred',
            },
        ),
    ]
