# Generated by Django 4.2.6 on 2023-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('emotion', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'emotion',
            },
        ),
    ]
